from Province_Detector import ProvinceDetector

reader = ProvinceDetector()

# print(reader.getProvince("Cropped_1.jpg"))

provinces = {
    "amnat_charoen": "อำนาจเจริญ",
    "ang_thong": "อ่างทอง",
    "bangkok": "กรุงเทพมหานคร",
    "bueng_kan": "บึงกาฬ",
    "buriram": "บุรีรัมย์",
    "chachoengsao": "ฉะเชิงเทรา",
    "chai_nat": "ชัยนาท",
    "chaiyaphum": "ชัยภูมิ",
    "chanthaburi": "จันทบุรี",
    "chiang_mai": "เชียงใหม่",
    "chiang_rai": "เชียงราย",
    "chonburi": "ชลบุรี",
    "chumphon": "ชุมพร",
    "kalasin": "กาฬสินธุ์",
    "kamphaeng_phet": "กำแพงเพชร",
    "kanchanaburi": "กาญจนบุรี",
    "khon_kaen": "ขอนแก่น",
    "krabi": "กระบี่",
    "lampang": "ลำปาง",
    "lamphun": "ลำพูน",
    "loei": "เลย",
    "lopburi": "ลพบุรี",
    "mae_hong_son": "แม่ฮ่องสอน",
    "maha_sarakham": "มหาสารคาม",
    "mukdahan": "มุกดาหาร",
    "nakhon_nayok": "นครนายก",
    "nakhon_pathom": "นครปฐม",
    "nakhon_phanom": "นครพนม",
    "nakhon_ratchasima": "นครราชสีมา",
    "nakhon_sawan": "นครสวรรค์",
    "nakhon_si_thammarat": "นครศรีธรรมราช",
    "nan": "น่าน",
    "narathiwat": "นราธิวาส",
    "nong_bua_lam_phu": "หนองบัวลำภู",
    "nong_khai": "หนองคาย",
    "nonthaburi": "นนทบุรี",
    "pathum_thani": "ปทุมธานี",
    "pattani": "ปัตตานี",
    "phang_nga": "พังงา",
    "phatthalung": "พัทลุง",
    "phayao": "พะเยา",
    "phetchabun": "เพชรบูรณ์",
    "phetchaburi": "เพชรบุรี",
    "phichit": "พิจิตร",
    "phitsanulok": "พิษณุโลก",
    "phra_nakhon_si_ayutthaya": "พระนครศรีอยุธยา",
    "phrae": "แพร่",
    "phuket": "ภูเก็ต",
    "prachinburi": "ปราจีนบุรี",
    "prachuap_khiri_khan": "ประจวบคีรีขันธ์",
    "ranong": "ระนอง",
    "ratchaburi": "ราชบุรี",
    "rayong": "ระยอง",
    "roi_et": "ร้อยเอ็ด",
    "sa_kaeo": "สระแก้ว",
    "sakon_nakhon": "สกลนคร",
    "samut_prakan": "สมุทรปราการ",
    "samut_sakhon": "สมุทรสาคร",
    "samut_songkhram": "สมุทรสงคราม",
    "saraburi": "สระบุรี",
    "satun": "สตูล",
    "si_sa_ket": "ศรีสะเกษ",
    "sing_buri": "สิงห์บุรี",
    "songkhla": "สงขลา",
    "sukhothai": "สุโขทัย",
    "suphanburi": "สุพรรณบุรี",
    "surat_thani": "สุราษฎร์ธานี",
    "surin": "สุรินทร์",
    "tak": "ตาก",
    "trang": "ตรัง",
    "trat": "ตราด",
    "ubon_ratchathani": "อุบลราชธานี",
    "udon_thani": "อุดรธานี",
    "uthai_thani": "อุทัยธานี",
    "uttaradit": "อุตรดิตถ์",
    "yala": "ยะลา",
    "yasothon": "ยโสธร"
}

print(len(provinces))